version: '3'

services:
  revers:
    build: revers
    restart: always

  default:
    build: default
    restart: always

  proxy:
    build: proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    restart: always